TestSystemManagement/TestSystemManagement/Controllers/MVC/TestDetailController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using TestSystemManagement.Models;
using TestSystemManagement.Repository;

namespace TestSystemManagement.Controllers.MVC
{
    public class TestDetailController : Controller
    {
        private readonly TestDetailRepository _repository = new TestDetailRepository();
        private readonly TestSystemManagementEntities _db = new TestSystemManagementEntities();

        [HttpPost]
        public JsonResult UploadFile()
        {
            if (Request.Files == null)
                return new JsonResult { Data = false, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

            var file = Request.Files[0];
            if (file != null)
            {
                var extension = Path.GetExtension(file.FileName);
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                try
                {
                    file.SaveAs(Path.Combine(Server.MapPath("~/App_Data"), fileName));
                    var path = Server.MapPath("~/App_Data/" + fileName);
                    if (extension == ".docx")
                        _repository.UploadWordFile(path);
                    if (extension == ".txt")
                        _repository.UploadTextFile(path);
                    if (extension == ".xlsx")
                        _repository.UploadExcelFile(path);
                }
                catch (Exception ex)
                {
                    return new JsonResult { Data = false, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                }
            }
            return new JsonResult { Data = true, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public ActionResult DownloadQuestion(int easy, int mid, int hard)
        {
            var resultEasy = _db.TestDetails
                .Where(x => x.TypeOfQuestion == Constant.EasyQuestion).OrderBy(x => Guid.NewGuid()).Take(easy);
            var resultMid = _db.TestDetails
                .Where(x => x.TypeOfQuestion == Constant.MidQuestion).OrderBy(x => Guid.NewGuid()).Take(mid);
            var resultHard = _db.TestDetails
                .Where(x => x.TypeOfQuestion == Constant.HardQuestion).OrderBy(x => Guid.NewGuid()).Take(hard);

            var result = resultEasy.Union(resultMid).Union(resultHard).ToList();

            return View("~/Views/Admin/DownloadQuestion.cshtml", result);
        }
    }
}

TestSystemManagement/TestSystemManagement/Views/Admin/CourseManage.cshtml
@{
    ViewBag.Title = "CourseService";
}

<main ng-controller="NewSubjectController">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Quản Lý Môn Thi</h3>
        </div>
        <div class="panel-body">
            <div class="row contain-wrapper">
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Tìm môn thi">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Tìm môn thi</button>
                        </span>
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
                <br /><br />
                <form class="col-md-12" name="AddNewSubjectForm" novalidate ng-submit="AddNewSubject()">
                    <div class="row">
                        <div class="input-field col-md-6">
                            <label for="SubjectName">Tên Môn</label>
                            <label for="SubjectName" ng-show="(AddNewSubjectForm.SubjectName.$dirty || Submitted) && AddNewSubjectForm.SubjectName.$error.required">Tên Môn Không Được Để Trống</label>
                            <input id="SubjectName" class="form-control" name="SubjectName" ng-class="Submitted?'ng-dirty':''" ng-model="SubjectData.SubjectName" type="text" required autofocus>
                        </div>
                        <div class="input-field  col-md-6">
                            <label for="SubjectCode">Mã Môn</label>
                            <label for="SubjectCode" ng-show="(AddNewSubjectForm.SubjectCode.$dirty || Submitted) && AddNewSubjectForm.SubjectCode.$error.required">Mã Môn Không Được Để Trống</label>
                            <input id="SubjectCode" class="form-control" name="SubjectCode" ng-class="Submitted?'ng-dirty':''" ng-model="SubjectData.SubjectCode" type="text" required autofocus>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col-md-6">
                            <label for="SecretCode">Mã Bí Mật</label>
                            <label for="SecretCode" ng-show="(AddNewSubjectForm.SecretCode.$dirty || Submitted) && AddNewSubjectForm.SecretCode.$error.required">Mã Bí Mật Không Được Để Trống</label>
                            <input id="SecretCode" class="form-control" name="SecretCode" ng-class="Submitted?'ng-dirty':''" ng-model="SubjectData.SecretCode" type="text" required autofocus>
                        </div>
                        <div class="input-field  col-md-6">
                            <label for="NoOfEasyQuestion">Số Lượng Câu Hỏi Dễ</label>
                            <label for="NoOfEasyQuestion" ng-show="(AddNewSubjectForm.NoOfEasyQuestion.$dirty || Submitted) && AddNewSubjectForm.NoOfEasyQuestion.$error.required">Số Lượng Câu Hỏi Dễ Không Được Để Trống</label>
                            <input id="NoOfEasyQuestion" class="form-control" name="NoOfEasyQuestion" ng-class="Submitted?'ng-dirty':''" ng-model="SubjectData.NoOfEasyQuestion" type="number" required autofocus>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field  col-md-6">
                            <label for="NoOfMediumQuestion">Số Lượng Câu Hỏi Trung Bình</label>
                            <label for="NoOfMediumQuestion" ng-show="(AddNewSubjectForm.NoOfMediumQuestion.$dirty || Submitted) && AddNewSubjectForm.NoOfMediumQuestion.$error.required">Số Lượng Câu Hỏi Trung Bình Không Được Để Trống</label>
                            <input id="NoOfMediumQuestion" class="form-control" name="NoOfMediumQuestion" ng-class="Submitted?'ng-dirty':''" ng-model="SubjectData.NoOfMediumQuestion" type="number" required autofocus>
                        </div>
                        <div class="input-field  col-md-6">
                            <label for="NoOfHardQuestion">Số Lượng Câu Hỏi Khó</label>
                            <label for="NoOfMediumQuestion" ng-show="(AddNewSubjectForm.NoOfHardQuestion.$dirty || Submitted) && AddNewSubjectForm.NoOfHardQuestion.$error.required">Số Lượng Câu Hỏi Khó Không Được Để Trống</label>
                            <input id="NoOfHardQuestion" class="form-control" name="NoOfHardQuestion" ng-class="Submitted?'ng-dirty':''" ng-model="SubjectData.NoOfHardQuestion" type="number" required autofocus>
                        </div>
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary" ng-hide="HideAddSubjectBtn">
                        Thêm Môn
                    </button>

                    <img src="/Content/img/hourglass.gif" ng-show="Loading" />
                </form>
            </div>
        </div>
    </div>
</main>
@section scripts{
    <script src="~/Scripts/app/Controller/SubjectController.js"></script>
}

TestSystemManagement/TestSystemManagement/Views/Admin/CreateQuestion.cshtml
@{
    ViewBag.Title = "CreateQuestion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main ng-controller="QuizController">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Quản Lý Câu Hỏi</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" class="form-control" ng-model="TestChildSubjectId" placeholder="Tìm kiếm đề thi">
                        <span class="input-group-btn">
                            <button class="btn btn-default" ng-click="searchQuestion()" type="button">Tìm kiếm đề thi</button>
                        </span>
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
                <div class="col-md-12" style="margin-top: 10px" ng-show="showSearchTable">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Mã Môn</th>
                            <th>Câu hỏi</th>
                            <th>Cập Nhật/Xóa</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="data in searchData">
                            <td>{{data.TestChildSubjectId}}</td>
                            <td><div data-ng-bind-html="data.Question"></div></td>
                            <td><a class="btn btn-primary" ng-click="GetQuestionDetail(data.Id)" href="/Admin/UpdateQuestionDetail/{{data.Id}}">Cập nhật</a> / <button class="btn btn-danger" ng-click="DeleteQuestion(data.Id)">Xóa</button></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="question-form">

                <form id="NewTextForm" name="NewTextForm" novalidate ng-submit="ImportTextQuiz()">
                    <br /><br />
                    <div class="answer" id="cloneArea">
                        <div class="row">
                            <div class="col-md-7">
                                <div class="input-field">
                                    <span>Câu Hỏi</span>
                                    <br />
                                    <textarea id="Question" name="Question" ng-model="ImportTextData.Question" class="materialize-textarea input-form" placeholder="Nhập câu hỏi" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                @*<label for="Question" ng-show="(NewTextForm.Question.$dirty || QuizFormSubmitted) && NewTextForm.Question.$error.required">Câu hỏi Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-4" style="margin-top: 20px">
                                <input id="TestChildSubjectId" name="TestChildSubjectId" ng-model="ImportTextData.TestChildSubjectId" class="form-control" placeholder="Nhập mã môn" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus>
                                <br />
                                <select id="TypeOfQuestion" class="form-control" name="TypeOfQuestion" ng-model="ImportTextData.TypeOfQuestion" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus>
                                    <option value="" disabled selected>Loại Câu Hỏi</option>
                                    <option value="1">Câu hỏi dễ</option>
                                    <option value="2">Câu hỏi trung bình</option>
                                    <option value="3">Câu hỏi khó</option>
                                </select>
                                <br />
                                @*<label for="TypeOfQuestion" ng-show="(NewTextForm.TypeOfQuestion.$dirty || QuizFormSubmitted) && NewTextForm.TypeOfQuestion.$error.required">Loại câu hỏi Không Được Để Trống</label>*@
                            </div>
                        </div>
                        <br /><br />
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án A</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="A" name="CorrectAnswer" />
                                    <textarea id="AnswerA" name="AnswerA" ng-model="ImportTextData.AnswerA" class="materialize-textarea answer-form pad10" placeholder="Đáp án a" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerA" ng-show="(NewTextForm.AnswerA.$dirty || QuizFormSubmitted) && NewTextForm.AnswerA.$error.required">Đáp án A Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án B</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="B" name="CorrectAnswer" />
                                    <textarea id="AnswerB" name="AnswerB" ng-model="ImportTextData.AnswerB" class="materialize-textarea answer-form pad10" placeholder="Đáp án b" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerB" ng-show="(NewTextForm.AnswerB.$dirty || QuizFormSubmitted) && NewTextForm.AnswerB.$error.required">Đáp án B Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án C</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="C" name="CorrectAnswer" />
                                    <textarea id="AnswerC" name="AnswerC" ng-model="ImportTextData.AnswerC" class="materialize-textarea answer-form pad10" placeholder="Đáp án c" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerC" ng-show="(NewTextForm.AnswerC.$dirty || QuizFormSubmitted) && NewTextForm.AnswerC.$error.required">Đáp án C Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án D</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="D" name="CorrectAnswer" />
                                    <textarea id="AnswerD" name="AnswerD" ng-model="ImportTextData.AnswerD" class="materialize-textarea answer-form pad10" placeholder="Đáp án d" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerD" ng-show="(NewTextForm.AnswerD.$dirty || QuizFormSubmitted) && NewTextForm.AnswerD.$error.required">Đáp án D Không Được Để Trống</label>*@
                            </div>
                        </div>
                    </div><br />
                    <button type="submit" class="btn btn-primary btn-block">
                        Thêm Câu Hỏi
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
@section scripts{
    <script src="~/Scripts/app/Controller/QuestionController.js"></script>
<script>
    CKEDITOR.replace('Question',
    {
        enterMode: CKEDITOR.ENTER_BR,
        width: 500,
        height: 200
    });
    CKEDITOR.replace('AnswerA',
    {
        enterMode: CKEDITOR.ENTER_BR,
        width: 400,
        height: 100
    });
    CKEDITOR.replace('AnswerB',
    {
        enterMode: CKEDITOR.ENTER_BR,
        width: 400,
        height: 100
    });
    CKEDITOR.replace('AnswerC',
    {
        enterMode: CKEDITOR.ENTER_BR,
        width: 400,
        height: 100
    });
    CKEDITOR.replace('AnswerD',
    {
        enterMode: CKEDITOR.ENTER_BR,
        width: 400,
        height: 100
    });
    CKFinder.setupCKEditor(null, '@Url.Content("~/Scripts/Lib-Js/ckfinder/")');
</script>
}

TestSystemManagement/TestSystemManagement/Views/Admin/DownloadQuestion.cshtml
@model IEnumerable<TestSystemManagement.Models.TestDetail>
@{
    ViewBag.Title = "In Đề Thi";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var questions = Model;
    var number = 1;
}
<div @*ng-controller="QuizController"*@>
    <form id="downloadQuestionForm" @*ng-submit="DownloadQuestion()"*@ action="@Url.Action("DownloadQuestion", "TestDetail")" method="POST">
        <div class="row" id="downloadQuestionInput" style="padding: 10%;">
            <div class="col-md-4">
                <input type="text" class="form-control" name="easy" placeholder="Số lượng câu hỏi dễ" ng-model="NumberOfEasyQuestion" />
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" name="mid" placeholder="Số lượng câu hỏi trung bình" ng-model="NumberOfMidQuestion" />
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" name="hard" placeholder="Số lượng câu hỏi khó" ng-model="NumberOfHardQuestion" />
            </div>

            <button type="submit" class="btn btn-primary" style="margin-top: 20px">Tải đề thi</button>
        </div>
    </form>
    <div class="row" style="padding: 10%;">
        @if (questions != null)
        {
            <a href="javascript:window.print()"><img src="~/Content/img/click-here-to-print.jpg" alt="print this page" id="print-button" style="margin-bottom:30px" /></a>
            foreach (var question in questions)
            {
                <p><span style="font-size: 20px; margin-bottom: 20px;color:blue">Câu Hỏi @number:@Html.Raw(question.Question)</span></p>
                <p>Đáp án A: @number: @Html.Raw(question.AnswerA)</p>
                <p>Đáp án B: @number: @Html.Raw(question.AnswerB)</p>
                <p>Đáp án C: @number: @Html.Raw(question.AnswerC)</p>
                <p>Đáp án D: @number: @Html.Raw(question.AnswerD)</p>
                <p style="margin-top:25px"></p>
                number++;
            }
        }
    </div>
</div>

TestSystemManagement/TestSystemManagement/Views/Admin/ImportQuestion.cshtml
<main ng-controller="ImportQuestionController">
    <div id="upload-form">
        <div class="container form-content">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Upload Câu Hỏi</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <form ng-submit="ImportQuestion()" novalidate name="ImportQuestionForm">
                            <div class="file-field input-field">
                                <div class="fileUpload btn btn-primary">
                                    <span>Vui lòng chọn file upload</span>
                                    <input type="file" class="upload" onchange="angular.element(this).scope().CheckFile(this)" required ng-class="Submitted?'ng-dirty':''">
                                    <span class="has-error" ng-show="(ImportQuestionForm.file.$dirty || Submitted) && ImportQuestionForm.file.$error.required">Vui Lòng Chọn File</span>
                                </div>
                                <button class="btn btn-primary" type="submit" ng-hide="HideUploadBtn">
                                    Upload
                                    <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                                </button>
                                <img src="/Content/img/hourglass.gif" ng-show="Loading" />
                            </div>
                        </form>
                    </div>

                    <div class="row">
                        {{fileMessage}}
                        {{Message}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@section scripts{
    <script src="~/Scripts/app/Controller/QuestionController.js"></script>
}

TestSystemManagement/TestSystemManagement/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Hệ Thống Quản Lý Ngân Hàng Câu Hỏi Trắc Nghiệm";
}

TestSystemManagement/TestSystemManagement/Views/Admin/QuestionManage.cshtml
<main ng-controller="ImportQuestionController">
    <div id="upload-form">
        <div class="container form-content">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Upload Câu Hỏi</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <form ng-submit="ImportQuestion()" novalidate name="ImportQuestionForm">
                            <div class="file-field input-field">
                                <div class="fileUpload btn btn-primary">
                                    <span>Vui lòng chọn file upload</span>
                                    <input type="file" class="upload" onchange="angular.element(this).scope().CheckFile(this)" required ng-class="Submitted?'ng-dirty':''">
                                    <span class="has-error" ng-show="(ImportQuestionForm.file.$dirty || Submitted) && ImportQuestionForm.file.$error.required">Vui Lòng Chọn File</span>
                                </div>
                                <button class="btn btn-primary" type="submit" ng-hide="HideUploadBtn">
                                    Upload
                                    <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                                </button>
                                <img src="/Content/img/hourglass.gif" ng-show="Loading" />
                            </div>
                        </form>
                    </div>

                    <div class="row">
                        {{fileMessage}}
                        {{Message}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<main ng-controller="QuizController">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Quản Lý Câu Hỏi</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" class="form-control" ng-model="TestChildSubjectId" placeholder="Tìm kiếm đề thi">
                        <span class="input-group-btn">
                            <button class="btn btn-default" ng-click="searchQuestion()" type="button">Tìm kiếm đề thi</button>
                        </span>
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
                <div class="col-md-12" style="margin-top: 10px" ng-show="showSearchTable">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Mã Môn</th>
                                <th>Câu hỏi</th>
                                <th>Cập Nhật/Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="data in searchData">
                                <td>{{data.TestChildSubjectId}}</td>
                                <td><div data-ng-bind-html="data.Question"></div></td>
                                <td><a class="btn btn-primary" ng-click="GetQuestionDetail(data.Id)" href="/Admin/UpdateQuestionDetail/{{data.Id}}">Cập nhật</a> / <button class="btn btn-danger" ng-click="DeleteQuestion(data.Id)">Xóa</button></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="question-form">

                <form id="NewTextForm" name="NewTextForm" novalidate ng-submit="ImportTextQuiz()">
                    <br /><br />
                    <div class="answer" id="cloneArea">
                        <div class="row">
                            <div class="col-md-7">
                                <div class="input-field">
                                    <span>Câu Hỏi</span>
                                    <br />
                                    <textarea id="Question" name="Question" ng-model="ImportTextData.Question" class="materialize-textarea input-form" placeholder="Nhập câu hỏi" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                @*<label for="Question" ng-show="(NewTextForm.Question.$dirty || QuizFormSubmitted) && NewTextForm.Question.$error.required">Câu hỏi Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-4" style="margin-top: 20px">
                                <input id="TestChildSubjectId" name="TestChildSubjectId" ng-model="ImportTextData.TestChildSubjectId" class="form-control" placeholder="Nhập mã môn" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus>
                                <br />
                                <select id="TypeOfQuestion" class="form-control" name="TypeOfQuestion" ng-model="ImportTextData.TypeOfQuestion" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus>
                                    <option value="" disabled selected>Loại Câu Hỏi</option>
                                    <option value="1">Câu hỏi dễ</option>
                                    <option value="2">Câu hỏi trung bình</option>
                                    <option value="3">Câu hỏi khó</option>
                                </select>
                                <br />
                                @*<label for="TypeOfQuestion" ng-show="(NewTextForm.TypeOfQuestion.$dirty || QuizFormSubmitted) && NewTextForm.TypeOfQuestion.$error.required">Loại câu hỏi Không Được Để Trống</label>*@
                            </div>
                        </div>
                        <br /><br />
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án A</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="A" name="CorrectAnswer" />
                                    <textarea id="AnswerA" name="AnswerA" ng-model="ImportTextData.AnswerA" class="materialize-textarea answer-form pad10" placeholder="Đáp án a" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerA" ng-show="(NewTextForm.AnswerA.$dirty || QuizFormSubmitted) && NewTextForm.AnswerA.$error.required">Đáp án A Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án B</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="B" name="CorrectAnswer" />
                                    <textarea id="AnswerB" name="AnswerB" ng-model="ImportTextData.AnswerB" class="materialize-textarea answer-form pad10" placeholder="Đáp án b" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerB" ng-show="(NewTextForm.AnswerB.$dirty || QuizFormSubmitted) && NewTextForm.AnswerB.$error.required">Đáp án B Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án C</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="C" name="CorrectAnswer" />
                                    <textarea id="AnswerC" name="AnswerC" ng-model="ImportTextData.AnswerC" class="materialize-textarea answer-form pad10" placeholder="Đáp án c" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerC" ng-show="(NewTextForm.AnswerC.$dirty || QuizFormSubmitted) && NewTextForm.AnswerC.$error.required">Đáp án C Không Được Để Trống</label>*@
                            </div>
                            <div class="col-md-6">
                                <div class="input-field question-detail">
                                    <span>Đáp án D</span>
                                    <br />
                                    <input type="checkbox" class="filled-in CorrectAnswer" value="D" name="CorrectAnswer" />
                                    <textarea id="AnswerD" name="AnswerD" ng-model="ImportTextData.AnswerD" class="materialize-textarea answer-form pad10" placeholder="Đáp án d" ng-class="QuizFormSubmitted?'ng-dirty':''" required autofocus></textarea>
                                </div>
                                <br /><br />
                                @*<label for="AnswerD" ng-show="(NewTextForm.AnswerD.$dirty || QuizFormSubmitted) && NewTextForm.AnswerD.$error.required">Đáp án D Không Được Để Trống</label>*@
                            </div>
                        </div>
                    </div><br />
                    <button type="submit" class="btn btn-primary btn-block">
                        Thêm Câu Hỏi
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
@section scripts{
    <script src="~/Scripts/app/Controller/QuestionController.js"></script>
    <script>
        CKEDITOR.replace('Question',
        {
            enterMode: CKEDITOR.ENTER_BR,
            width: 500,
            height: 200
        });
        CKEDITOR.replace('AnswerA',
        {
            enterMode: CKEDITOR.ENTER_BR,
            width: 400,
            height: 100
        });
        CKEDITOR.replace('AnswerB',
        {
            enterMode: CKEDITOR.ENTER_BR,
            width: 400,
            height: 100
        });
        CKEDITOR.replace('AnswerC',
        {
            enterMode: CKEDITOR.ENTER_BR,
            width: 400,
            height: 100
        });
        CKEDITOR.replace('AnswerD',
        {
            enterMode: CKEDITOR.ENTER_BR,
            width: 400,
            height: 100
        });
        CKFinder.setupCKEditor(null, '@Url.Content("~/Scripts/Lib-Js/ckfinder/")');
    </script>
}